name: On Release

on:
  release:
    types:
      - created

jobs:
  publish:
    permissions:
      contents: read
      packages: write
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Check out Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Publish package
        run: ./gradlew publish
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
