name: On Release

on:
  release:
    types:
      - created

jobs:
  build-and-deploy:
    name: Build and Deploy on Release
    runs-on: ubuntu-latest

    steps:
      - name: Check out Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '8'

      - name: Build Project
        run: |
          ./gradlew assemble
